name:                csv2influx
version:             0.1.0.0
github:              "dustin/csv2influx"
license:             BSD3
author:              "Dustin Sallings"
maintainer:          "dustin@spy.net"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dustin/csv2influx#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- cassava
- vector
- optparse-applicative

default-extensions:
  - OverloadedStrings
  - RecordWildCards
  - NamedFieldPuns
  - LambdaCase

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  csv2influx:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - csv2influx

tests:
  csv2influx-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - csv2influx
    - HUnit
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-golden
    - QuickCheck
